import { expect, test } from '@playwright/test'

test.use({ viewport: { width: 390, height: 844 }, reducedMotion: 'reduce' })

test('expanded phone controls scroll independently and keep the model visible', async ({ page }) => {
  await page.goto('./#scene-lab')
  const lab = page.locator('#scene-lab')
  await lab.getByRole('button', { name: '展开场景', exact: true }).click()
  await expect(lab.locator('.scene-lab-body')).toHaveAttribute('data-status', 'ready')
  const canvas = lab.locator('.simulation-canvas canvas')
  const originalCanvas = await canvas.elementHandle()
  const panel = lab.locator('.simulation-panel')
  const initial = await canvas.boundingBox()
  expect(initial!.height).toBeGreaterThan(180)

  const elevation = lab.getByRole('slider', { name: '设计标高', exact: true })
  await elevation.focus()
  await elevation.press('End')
  await expect(elevation).toHaveValue('30')
  await lab.locator('.scene-object-list button').first().click()
  await expect(lab.getByRole('region', { name: '选中对象详情' })).toBeFocused()
  await expect.poll(() => panel.evaluate((el) => el.scrollTop)).toBeGreaterThan(0)
  const after = await canvas.boundingBox()
  expect(after!.y).toBeCloseTo(initial!.y, 0)
  expect(after!.y + after!.height).toBeLessThan(844)
  expect(after!.height).toBeCloseTo(initial!.height, 0)

  await lab.getByRole('button', { name: '收起控制面板', exact: true }).click()
  await expect(panel).toBeHidden()
  expect((await canvas.boundingBox())!.height).toBeGreaterThan(initial!.height)
  await lab.getByRole('button', { name: '展开控制面板', exact: true }).click()
  await expect(panel).toBeVisible()
  await expect(elevation).toHaveValue('30')
  expect(await originalCanvas!.evaluate((el) => el.isConnected)).toBe(true)

  await lab.getByRole('button', { name: '拖动视角', exact: true }).click()
  await expect(canvas).toHaveCSS('touch-action', 'none')
  await lab.getByRole('button', { name: '退出拖动', exact: true }).click()
  await expect(canvas).toHaveCSS('touch-action', 'pan-y')
  await page.keyboard.press('Escape')
  await expect(lab).toHaveAttribute('role', 'region')
  await expect(lab.getByRole('button', { name: '展开场景', exact: true })).toBeFocused()
  await expect(page.locator('body')).not.toHaveClass(/scene-expanded/)
})

test('a small phone and landscape retain reachable controls without page overflow', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('./#scene-lab')
  const lab = page.locator('#scene-lab')
  await lab.getByRole('button', { name: '展开场景', exact: true }).click()
  await expect(lab.locator('.scene-lab-body')).toHaveAttribute('data-status', 'ready')
  const panel = lab.locator('.simulation-panel')
  expect((await panel.boundingBox())!.height).toBeGreaterThan(80)
  const selector = lab.locator('.scene-selector')
  await selector.getByRole('button', { name: /园区三维/ }).click()
  await expect(lab.locator('.scene-lab-body')).toHaveAttribute('data-scene', 'campus')
  await expect(lab.getByRole('slider', { name: '日照时刻' })).toBeEnabled()
  await lab.getByRole('button', { name: '收起控制面板', exact: true }).click()
  await page.setViewportSize({ width: 844, height: 390 })
  await expect(panel).toBeVisible()
  const model = await lab.locator('.simulation-stage').boundingBox()
  const controls = await panel.boundingBox()
  expect(model!.x + model!.width).toBeLessThanOrEqual(controls!.x + 1)
  expect(model!.height).toBeGreaterThan(120)
  expect(controls!.height).toBeGreaterThan(120)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  const close = await lab.getByRole('button', { name: '收起场景', exact: true }).boundingBox()
  expect(close!.y + close!.height).toBeLessThan(390)
})

test('English mobile controls remain operable with long labels', async ({ page }) => {
  await page.goto('./#scene-lab')
  await page.getByRole('button', { name: 'Switch to English', exact: true }).click()
  const lab = page.locator('#scene-lab')
  await lab.getByRole('button', { name: 'Expand scene', exact: true }).click()
  await expect(lab.locator('.scene-lab-body')).toHaveAttribute('data-status', 'ready')
  const panel = lab.locator('.simulation-panel')
  await expect(lab.getByRole('button', { name: 'Collapse controls', exact: true })).toBeVisible()
  await lab.getByRole('button', { name: 'Simulation', exact: true }).click()
  const progress = lab.getByRole('slider', { name: 'Construction progress', exact: true })
  await progress.focus()
  await progress.press('End')
  await expect(progress).toHaveValue('100')
  expect(await panel.evaluate((el) => el.scrollWidth <= el.clientWidth)).toBe(true)
  const model = await lab.locator('.simulation-stage').boundingBox()
  expect(model!.y).toBeGreaterThanOrEqual(0)
  expect(model!.y + model!.height).toBeLessThan(844)
})
