import { mkdir } from 'node:fs/promises'
import { test, expect } from '@playwright/test'

test('mobile scrolling stays available and offscreen parameters still update analysis', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('./#scene-lab')
  const lab = page.locator('#scene-lab')
  await lab
    .locator('.scene-selector')
    .getByRole('button', { name: /水利孪生/ })
    .click()
  await expect(lab.locator('.scene-lab-body')).toHaveAttribute('data-status', 'ready')
  const canvas = lab.locator('.simulation-canvas canvas')
  await expect(canvas).toHaveCSS('touch-action', 'pan-y')
  await lab.getByRole('button', { name: '拖动视角', exact: true }).click()
  await expect(canvas).toHaveCSS('touch-action', 'none')
  await lab.getByRole('button', { name: '退出拖动', exact: true }).click()
  await expect(canvas).toHaveCSS('touch-action', 'pan-y')
  await lab.locator('.simulation-panel').evaluate((el) => el.scrollIntoView({ block: 'start' }))
  await expect.poll(() => canvas.evaluate((el) => el.getBoundingClientRect().bottom)).toBeLessThanOrEqual(1)
  const level = lab.getByRole('slider', { name: '分析水位' })
  await level.focus()
  await level.press('End')
  await expect(level).toHaveValue('32')
  await expect(lab.locator('.scene-metrics')).toContainText('32m')
  await expect(lab.locator('.scene-object-list .is-affected')).toHaveCount(3)
  await level.press('Home')
  await expect(lab.locator('.scene-object-list .is-affected')).toHaveCount(0)
  await lab.getByRole('button', { name: '展开场景', exact: true }).click()
  await lab.locator('.simulation-stage').scrollIntoViewIfNeeded()
  await mkdir('tmp/scenario-upgrade', { recursive: true })
  await page.screenshot({ path: 'tmp/scenario-upgrade/05-mobile-water.png' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.keyboard.press('Escape')
  await expect(lab).toHaveAttribute('role', 'region')
  await expect(page.locator('body')).not.toHaveClass(/scene-expanded/)
})

test('construction playback advances the actual progress and can pause and resume', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('./#scene-lab')
  const lab = page.locator('#scene-lab')
  const progress = lab.getByRole('slider', { name: '施工进度' })
  await expect(progress).toBeEnabled()
  await lab.getByRole('button', { name: '播放施工过程', exact: true }).click()
  await expect.poll(async () => Number(await progress.inputValue())).toBeGreaterThan(2)
  await lab.getByRole('button', { name: '暂停过程', exact: true }).click()
  const held = await progress.inputValue()
  await page.waitForTimeout(450)
  await expect(progress).toHaveValue(held)
  await lab.getByRole('button', { name: '播放施工过程', exact: true }).click()
  await expect.poll(async () => Number(await progress.inputValue())).toBeGreaterThan(Number(held))
  await lab.getByRole('button', { name: '暂停过程', exact: true }).click()
})

test('a lost scene graphics context can be retried without duplicating the canvas', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('./#scene-lab')
  const lab = page.locator('#scene-lab')
  await expect(lab.locator('.scene-lab-body')).toHaveAttribute('data-status', 'ready')
  await lab.locator('.simulation-canvas canvas').evaluate((el: HTMLCanvasElement) => {
    el.getContext('webgl2')!.getExtension('WEBGL_lose_context')!.loseContext()
  })
  await expect(lab.locator('.scene-lab-body')).toHaveAttribute('data-status', 'error')
  await lab.getByRole('button', { name: '重新加载', exact: true }).click()
  await expect(lab.locator('.scene-lab-body')).toHaveAttribute('data-status', 'ready')
  await expect(lab.locator('.simulation-canvas canvas')).toHaveCount(1)
  await expect(lab.getByRole('slider', { name: '设计标高' })).toBeEnabled()
  expect(errors).toEqual([])
})
