export const labCopy: Record<string, string> = {
  参数与对象: 'Controls & objects',
  收起控制面板: 'Collapse controls',
  展开控制面板: 'Expand controls',
  场景播放与拖动: 'Scene playback and drag controls',
  可查看: 'View details',
  未检查: 'Not inspected',
  受影响: 'Affected',
  '点选场景对象，查看详细信息。': 'Select a scene object to view its details.',
  返回场景全览: 'Return to the full scene',
  场景模式: 'Scene mode',
  场景总览: 'Overview',
  病害复核: 'Defect review',
  分析结果: 'Analysis',
  巡检过程: 'Inspection',
  过程推演: 'Simulation',
  水位情景: 'Water-level scenarios',
  低水位: 'Low water',
  高水位: 'High water',
  漫坝情景: 'Overtopping',
  施工进度: 'Construction progress',
  水位推演进度: 'Water-level simulation progress',
  暂停过程: 'Pause simulation',
  播放施工过程: 'Play construction sequence',
  播放水位推演: 'Play water-level simulation',
  巡检覆盖: 'Inspection coverage',
  重新巡检: 'Restart inspection',
  开始巡检: 'Start inspection',
  下一检查点: 'Next checkpoint',
  叠加原始地形: 'Overlay original terrain',
  园区图层: 'Campus layers',
  建筑: 'Buildings',
  道路: 'Roads',
  绿化: 'Landscaping',
  楼层剖切: 'Floor section',
  场景分析指标: 'Scene analysis metrics',
  检查记录: 'Inspection records',
  建筑目录: 'Building directory',
  分析对象: 'Analysis objects',
  病害状态筛选: 'Filter by defect status',
  全部: 'All',
  '当前筛选下没有记录。': 'No records match this filter.',
  选中对象详情: 'Selected object details',
  标记已复核: 'Mark as reviewed',
  '已按系统设置减少动态效果，可用滑块和单步操作查看结果。':
    'Motion is reduced to match your system preference. Use sliders and step controls to explore the results.',
  '点选模型或列表可定位；开启拖动后可自由观察。':
    'Select a model or list item to focus it. Enable drag mode to orbit freely.',
  珊瑚: 'Coral',
  琥珀: 'Amber',
  白色: 'White',
  蓝: 'Blue',
  收起场景: 'Collapse scene',
  展开场景: 'Expand scene',
  收起: 'Collapse',
  展开体验: 'Expand view',
  '园区为本地概念模型，展示超图相关业务交互思路，未接入实景模型或 SuperMap 服务。':
    'This local concept campus demonstrates interaction patterns relevant to SuperMap projects. No reality-capture model or SuperMap service is connected.',
  '静态水位与栅格连通性演示，不计算降雨、流速或洪水到达时间。':
    'A demonstration of static water levels and grid connectivity. Rainfall, flow velocity and flood arrival time are not calculated.',
  '采用合成地形和预设施工范围；方量为网格近似值，不用于工程计量。':
    'Synthetic terrain with a predefined construction boundary. Volumes are grid-based approximations, not engineering measurements.',
  '病害与检查任务为预设示例，展示发现及复核流程，未接入图像识别模型。':
    'Preset defects and inspection tasks demonstrate discovery and review. No image-recognition model is connected.',
  '挖填之间，看见施工过程。': 'See the process, from cut to fill.',
  '调整设计标高，查看局部挖填分区与方量。拖动施工进度，比较原始地形和施工后的场地。':
    'Adjust the design elevation to explore cut and fill zones and volumes. Scrub the construction sequence to compare the original terrain with the finished site.',
  '珊瑚 · 开挖区域': 'Coral · Cut zones',
  '青绿 · 填筑区域': 'Mint · Fill zones',
  '琥珀 · 施工运输': 'Amber · Construction haulage',
  '无人机逐站检查桥梁构件。发现示例病害后，点选定位、观察细节并完成复核。':
    'A drone inspects bridge components station by station. Select a discovered example defect to locate it, inspect its details and complete the review.',
  '琥珀 · 待复核病害': 'Amber · Defects pending review',
  '蓝色 · 已复核病害': 'Blue · Reviewed defects',
  '从水位，推演影响范围。': 'From water level to impact.',
  '基于水源连通性与坝顶高程，分析静态水位下的淹没范围、水深及受影响建筑。':
    'Explore inundation extent, water depth and affected buildings at a static water level, accounting for source connectivity and dam-crest elevation.',
  '浅蓝 · 较浅积水': 'Light blue · Shallow water',
  '深蓝 · 较深积水': 'Dark blue · Deeper water',
  '琥珀 · 受影响建筑': 'Amber · Affected buildings',
  园区三维: '3D campus',
  '从园区全貌，到每栋建筑。': 'From the campus to each building.',
  '点选建筑查看示例属性，切换道路与绿化图层，观察楼层剖切和日照示意。':
    'Select a building to inspect example properties, toggle roads and landscaping, and explore floor sections and illustrative daylight.',
  日照时刻: 'Illustrative daylight time',
  '青绿 · 选中建筑': 'Mint · Selected building',
  '白色 · 建筑模型': 'White · Building models',
  '蓝色 · 园区景观': 'Blue · Campus landscape',
  风机数量: 'Turbines',
  台: 'units',
  '风场为本地合成，叶片转速仅作视觉表达。':
    'A locally generated wind farm. Blade speed is a visual illustration.',
  '园区三维 · 超图相关能力演示': '3D campus · SuperMap-related capabilities',
  '以概念园区展示建筑查询、图层管理、楼层剖切和日照示意，预留后续实景三维数据接入。':
    'A concept campus demonstrating building queries, layer management, floor sections and illustrative daylight, with scope for future reality-capture data integration.',
  探索园区场景: 'Explore the campus',
  概念演示: 'Concept demo',
}
