export const sceneDefinitions = {
  earthwork: {
    name: '土石方调配',
    code: '01 / TERRAIN',
    title: '挖填之间，看见施工过程。',
    description: '调整设计标高，查看局部挖填分区与方量。拖动施工进度，比较原始地形和施工后的场地。',
    parameter: '设计标高',
    min: 8,
    max: 30,
    initial: 18,
    unit: 'm',
    legend: ['珊瑚 · 开挖区域', '青绿 · 填筑区域', '琥珀 · 施工运输'],
  },
  uav: {
    name: '桥梁巡检',
    code: '02 / INSPECTION',
    title: '沿着航线，发现细节。',
    description: '无人机逐站检查桥梁构件。发现示例病害后，点选定位、观察细节并完成复核。',
    parameter: '巡航速度',
    min: 20,
    max: 150,
    initial: 65,
    unit: '%',
    legend: ['青绿 · 巡检航线', '琥珀 · 待复核病害', '蓝色 · 已复核病害'],
  },
  'offshore-wind': {
    name: '海上风电',
    code: '03 / OFFSHORE',
    title: '让海风，变得可见。',
    description: '九台参数化风机组成的海上风场。调节模拟风速，查看叶片转动变化与海缆连接关系。',
    parameter: '模拟风速',
    min: 0,
    max: 20,
    initial: 8,
    unit: 'm/s',
    legend: ['白色 · 风机阵列', '青绿 · 海缆连接', '蓝色 · 程序化海面'],
  },
  'water-twin': {
    name: '水利孪生',
    code: '04 / HYDROLOGY',
    title: '从水位，推演影响范围。',
    description: '基于水源连通性与坝顶高程，分析静态水位下的淹没范围、水深及受影响建筑。',
    parameter: '分析水位',
    min: 2,
    max: 32,
    initial: 12,
    unit: 'm',
    legend: ['浅蓝 · 较浅积水', '深蓝 · 较深积水', '琥珀 · 受影响建筑'],
  },
  campus: {
    name: '园区三维',
    code: '05 / CAMPUS',
    title: '从园区全貌，到每栋建筑。',
    description: '点选建筑查看示例属性，切换道路与绿化图层，观察楼层剖切和日照示意。',
    parameter: '日照时刻',
    min: 8,
    max: 18,
    initial: 14,
    unit: ':00',
    legend: ['青绿 · 选中建筑', '白色 · 建筑模型', '蓝色 · 园区景观'],
  },
} as const

export type SceneKind = keyof typeof sceneDefinitions
export function isSceneKind(value: string): value is SceneKind {
  return Object.hasOwn(sceneDefinitions, value)
}
