export const bridgeText = {
  deckCrack: '桥面裂缝',
  girderSpall: '梁体混凝土剥落',
  towerCrack: '桥塔表面裂缝',
  bearingRust: '支座表面锈蚀',
  deckLocation: '西侧桥跨 · 桥面铺装',
  girderLocation: '主跨 · 南侧梁体',
  towerLocation: '东侧桥塔 · 南侧立柱',
  bearingLocation: '东侧桥墩 · 支座外侧',
  crack: '裂缝',
  spall: '混凝土剥落',
  rust: '表面锈蚀',
  deckNote: '连续折线与分支纹理，用于近距离定位和人工复核演示。',
  girderNote: '剥落轮廓与局部露筋为程序几何示意，未加载真实影像。',
  towerNote: '桥塔外表面纵向裂缝示意，观察位置位于构件外侧。',
  bearingNote: '支座外表面的不规则锈斑示意，颜色不用于判定病害等级。',
  point1: '检查点 01',
  point2: '检查点 02',
  point3: '检查点 03',
  point4: '检查点 04',
  waiting: '等待到站观察',
  type: '病害类型',
  location: '构件位置',
  coordinates: '局部坐标',
  evidence: '发现依据',
  evidenceValue: '近距、视向与无遮挡检查',
  data: '数据说明',
  dataValue: '预设示例 · 非 AI 识别结果',
  scale: '尺寸说明',
  scaleValue: '局部纹理适度放大，未作工程量测',
  note: '观察说明',
  status: '复核状态',
  pending: '待人工复核',
  reviewed: '已完成演示复核',
  points: '检查点',
  found: '已发现',
  pendingCount: '待复核',
  reviewedCount: '已复核',
  bridgeLength: '桥梁示意长度',
  initialMessage: '选择施工 / 巡检过程开始巡检，或使用下一检查点逐站观察。病害为预设演示。',
  initialShort: '选择巡检过程开始，或使用下一检查点逐站观察。',
  flying: '无人机正沿航段接近下一个检查位置。',
  observing: '已到检查位置，正在确认观察距离、视向和遮挡关系。',
  foundMessage: '发现示例病害：点击高亮标记或对象列表定位，查看细节后完成复核。',
  pausedMessage: '巡检已暂停，保留当前检查结果；可继续巡检或逐站观察。',
  complete: '四个检查点已完成观察，可逐项查看并复核示例病害。',
  allReviewed: '四项示例病害已完成复核。重置后可重新体验巡检。',
  inspectMode: '当前为静态观察模式，已发现病害可点选查看。',
} as const

export const bridgeCopy: Record<string, string> = {
  [bridgeText.deckCrack]: 'Deck crack',
  [bridgeText.girderSpall]: 'Girder concrete spalling',
  [bridgeText.towerCrack]: 'Tower surface crack',
  [bridgeText.bearingRust]: 'Bearing surface corrosion',
  [bridgeText.deckLocation]: 'West span · deck pavement',
  [bridgeText.girderLocation]: 'Main span · south girder',
  [bridgeText.towerLocation]: 'East tower · south column',
  [bridgeText.bearingLocation]: 'East pier · outer bearing',
  [bridgeText.crack]: 'Crack',
  [bridgeText.spall]: 'Concrete spalling',
  [bridgeText.rust]: 'Surface corrosion',
  [bridgeText.deckNote]: 'A branching line pattern demonstrates close inspection and manual review.',
  [bridgeText.girderNote]: 'Spalling and exposed reinforcement are generated geometry, without real imagery.',
  [bridgeText.towerNote]: 'Illustrative vertical cracking on the outer face of a bridge tower.',
  [bridgeText.bearingNote]: 'Illustrative irregular corrosion patches; color does not indicate severity.',
  [bridgeText.point1]: 'Checkpoint 01',
  [bridgeText.point2]: 'Checkpoint 02',
  [bridgeText.point3]: 'Checkpoint 03',
  [bridgeText.point4]: 'Checkpoint 04',
  [bridgeText.waiting]: 'Awaiting close observation',
  [bridgeText.type]: 'Defect type',
  [bridgeText.location]: 'Component',
  [bridgeText.coordinates]: 'Local coordinates',
  [bridgeText.evidence]: 'Discovery criteria',
  [bridgeText.evidenceValue]: 'Proximity, viewing direction and clear line of sight',
  [bridgeText.data]: 'Data source',
  [bridgeText.dataValue]: 'Preset example · not AI detection',
  [bridgeText.scale]: 'Size reference',
  [bridgeText.scaleValue]: 'Detail exaggerated for visibility; not an engineering measurement',
  [bridgeText.note]: 'Observation',
  [bridgeText.status]: 'Review status',
  [bridgeText.pending]: 'Awaiting manual review',
  [bridgeText.reviewed]: 'Demo review complete',
  [bridgeText.points]: 'Checkpoints',
  [bridgeText.found]: 'Discovered',
  [bridgeText.pendingCount]: 'Pending review',
  [bridgeText.reviewedCount]: 'Reviewed',
  [bridgeText.bridgeLength]: 'Illustrative bridge length',
  [bridgeText.initialMessage]:
    'Start the inspection process or advance one checkpoint at a time. Defects are preset examples.',
  [bridgeText.initialShort]: 'Start the inspection process or advance one checkpoint at a time.',
  [bridgeText.flying]: 'The drone is approaching the next inspection station along its route.',
  [bridgeText.observing]: 'At the station: checking proximity, viewing direction and line of sight.',
  [bridgeText.foundMessage]: 'Example defect found. Select its marker or list item to inspect and review it.',
  [bridgeText.pausedMessage]: 'Inspection paused. Results are retained; resume or advance one checkpoint.',
  [bridgeText.complete]: 'All four checkpoints observed. Inspect and review each example defect.',
  [bridgeText.allReviewed]: 'All four example defects reviewed. Reset to repeat the inspection.',
  [bridgeText.inspectMode]: 'Static observation mode. Select a discovered defect to inspect it.',
}
