export const campusCopy: Record<string, string> = {
  'A01 · 创新总部': 'A01 · Innovation headquarters',
  'A02 · 智算研发': 'A02 · AI research',
  'A03 · 联合实验室': 'A03 · Joint laboratory',
  'B01 · 智造工坊': 'B01 · Smart manufacturing',
  'B02 · 中试中心': 'B02 · Pilot production',
  'A04 · 创业办公': 'A04 · Startup offices',
  'C01 · 共享客厅': 'C01 · Community hub',
  'C02 · 数据中心': 'C02 · Data center',
  总部办公: 'Headquarters',
  算法研发: 'AI research',
  联合实验: 'Joint laboratory',
  智能制造: 'Smart manufacturing',
  中试验证: 'Pilot production',
  企业孵化: 'Startup incubator',
  公共服务: 'Public amenities',
  数据服务: 'Data services',
  用地面积: 'Site area',
  建筑数量: 'Buildings',
  示意总建筑面积: 'Illustrative gross floor area',
  示意时刻: 'Illustrative time',
  建筑用途: 'Building use',
  建筑层数: 'Floors',
  建筑高度: 'Building height',
  建筑占地: 'Building footprint',
  示意建筑面积: 'Illustrative floor area',
  数据来源: 'Data source',
  当前视图: 'Current view',
  完整建筑: 'Full building',
  半高剖切: 'Half-height section',
  参数化概念模型: 'Parametric concept model',
  栋: 'buildings',
  '概念园区 · 1 单位 = 10 米。建筑属性来自模型几何；未加载实景倾斜摄影或 SuperMap 服务。':
    'Concept campus · 1 unit = 10 m. Building properties are derived from model geometry; no photogrammetry or SuperMap service is loaded.',
  '选择建筑查看几何属性；开启剖切可观察楼板。光照与投影用于时刻示意，不代表真实日照分析。':
    'Select a building to inspect its geometry; enable section view to reveal floor plates. Lighting and projected shadows illustrate time of day, not a site-specific solar study.',
  '沿园区道路漫游，观察建筑与景观的空间关系。车辆为演示动画，不代表实时运营数据。':
    'Tour the campus roads to explore buildings and landscape. Vehicles are illustrative animation, not live operations data.',
}
