export const earthworkCopy: Record<string, string> = {
  挖方量: 'Cut volume',
  填方量: 'Fill volume',
  余缺方量: 'Net surplus',
  施工完成: 'Completed',
  原始地形: 'Original terrain',
  设计完成面: 'Finished design surface',
  施工过程: 'Construction process',
  '开挖区 · 山体削坡': 'Cut zone · hillside excavation',
  '填筑区 · 场地抬升': 'Fill zone · ground raising',
  '珊瑚区域 / 削方作业': 'Coral area / excavation',
  '青绿区域 / 分层回填': 'Teal area / layered fill',
  '开挖区 · 当前无挖方': 'Cut zone · no excavation required',
  '填筑区 · 当前无填方': 'Fill zone · no fill required',
  该标高下无需开挖: 'No excavation needed at this elevation',
  该标高下无需填筑: 'No fill needed at this elevation',
  分析状态: 'Analysis status',
  '该设计标高下无挖方。': 'No excavation is needed at this design elevation.',
  '该设计标高下无填方。': 'No fill is needed at this design elevation.',
  原始高程: 'Original elevation',
  设计标高: 'Design elevation',
  当前高程: 'Current elevation',
  施工阶段: 'Construction phase',
  区域面积: 'Zone area',
  总作业面积: 'Total work area',
  栅格精度: 'Grid resolution',
  '原始地形与设计面叠加；切换挖填分析查看削坡与回填区域。':
    'Original terrain with the design surface; switch to cut/fill analysis to inspect excavation and fill.',
  '合成地形 · 方量按 2.5 m 栅格积分，正余量表示外运、负余量表示借方。':
    'Synthetic terrain · volumes integrated on a 2.5 m grid; a positive net volume is exported, a negative balance requires imported fill.',
}
